:consumer_key: jlZDYpqnCbU9mvGs8STWIw
:consumer_secret: 8UIPSnlU4K5veH4xhJ0W7zUUO36vHiJnUXo8K9KAOl0
:oauth_token: 572241558-b6oKh2wkCnTRAud0HW2B01Fnsl35wM3vX3G3AsoH
:oauth_token_secret: WuCCJ13uR8R6OYvKWchy0SyLrRjWcHBYLWIchmiYA